name: Eleventy Build
on:
  schedule:
  - cron: '0 1,16-20 * * *'

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: npm install
      - run: npm run build-action
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          PUBLISH_DIR: _site 
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}