name: Eleventy Build
on:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with: 
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          PUBLISH_DIR: _site 
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}